### ISSUE TITLE
f-word

### ISSUE THREAD

**Issue by AMAG-AB** [emidan19/deep-tempest#6]
If you don't know how to open source, don't open source！！！

**Comment by git-artes** [comment]
Not sure what you mean by this comment, but we've got a long history of publishing open-source software for the research we do. In any case, as the license states clearly, the code is provided "as is" without any warranty. If you can't make it work, we will, time permitting, try to help you. Sadly, this last couple of months have been very busy for us, and have not had to the time to answer the issues that has been opened. Please be patient.
